In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# Exploratory Data Analysis (EDA)

import joblib

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error
from colorama import Fore

## Task info

Your task

Implement a machine learning system that predicts being diagnosed with heart disease

1) Apply EDA to extract useful insights
2) Build your preprocessing pipeline consisting of scaling, label-encoding, one-hot encoding
3) Try the 3 models we covered logistic regression, svm & knn
 
Evaluate your model accuracy, precesion, recall, ......

Kindly deploy on a streamlit app

In [2]:
os.listdir('data/raw/')

['Heart-Disease-Patients-Records.csv']

In [3]:
df = pd.read_csv('data/preprocessed-data/preprocessed-data.csv')

# Data info
- -EDA-1 = 
- A /data/raw/Exam_Score_Prediction.csv 
- B data/feature eng data/feature_eng_data.csv

- -Pre-processed-2
- A data/feature eng data/feature_eng_data.csv
- B data/preprocessed data/pre-processed_data.csv

- -Machine-learning-3 = 
- A /data/preprocessed data/pre-processed_data.csv
- B /artifacts/svm_pipeline.pkl

In [4]:
df.sample(2)

,age,chest_pain_type,resisting_blood_pressure,cholesterol_level,max_heart_rate_achieved,st_depression,num_major_vessels,thalassemia,diagnosis,sex_female,...,fasting_blood_sugar_higher than 120mg/ml,fasting_blood_sugar_lower than 120mg/ml,rest_ecg_ST-T wave abnormality,rest_ecg_left ventricular hypertrophy,rest_ecg_normal,st_slope_downsloping,st_slope_flat,st_slope_upsloping,exercise_induced_angina_no,exercise_induced_angina_yes
207,41,2,112,250,179,0.0,0,1,Un-Diagnosed,0,...,0,1,1,0,0,1,0,0,1,0
212,50,3,150,243,128,2.6,0,2,Diagnosed,0,...,0,1,0,0,1,0,1,0,1,0

In [5]:
df.shape

(1024, 21)

In [6]:
df.columns

Index(['age', 'chest_pain_type', 'resisting_blood_pressure',
       'cholesterol_level', 'max_heart_rate_achieved', 'st_depression',
       'num_major_vessels', 'thalassemia', 'diagnosis', 'sex_female',
       'sex_male', 'fasting_blood_sugar_higher than 120mg/ml',
       'fasting_blood_sugar_lower than 120mg/ml',
       'rest_ecg_ST-T wave abnormality',
       'rest_ecg_left ventricular hypertrophy', 'rest_ecg_normal',
       'st_slope_downsloping', 'st_slope_flat', 'st_slope_upsloping',
       'exercise_induced_angina_no', 'exercise_induced_angina_yes'],
      dtype='object')

# Split freatures into X and y

## Die sicherere Lösung für deinen Code:
Damit dein Modell wirklich medizinisch lernt, solltest du beide Diagnose-Spalten aus X entfernen:

In [7]:
# Wir löschen BEIDE Diagnose-Spalten aus X
X = df.drop(columns=['diagnosis_Diagnosed', 'diagnosis_Un-Diagnosed'])

# Und setzen eine davon als unser Ziel y
y = df['diagnosis_Diagnosed']

KeyError: "['diagnosis_Diagnosed', 'diagnosis_Un-Diagnosed'] not found in axis"

In [ ]:
X.shape

(1024, 20)

### Split inti training and testing

In [ ]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.20, random_state= 42)

Model Selection
- Ensemble models =  kombiniert mehrere Einzelmodelle, um genauere Vorhersagen zu treffen als ein einzelnes Modell allein

In [ ]:
knn_model = KNeighborsRegressor( n_neighbors= 1)

In [ ]:
X_train.shape

(819, 20)

In [ ]:
X_test.shape

(205, 20)

In [ ]:
y_test

525    1
357    1
444    0
31     0
618    1
      ..
542    1
903    0
528    0
294    1
745    1
Name: diagnosis_Diagnosed, Length: 205, dtype: int64

In [ ]:
y_train

137    0
377    1
388    0
824    0
767    0
      ..
106    1
270    0
860    1
435    1
102    0
Name: diagnosis_Diagnosed, Length: 819, dtype: int64

In [ ]:
knn_model.fit( X_train, y_train)

KNeighborsRegressor(n_neighbors=1)

In [ ]:
y_pred_train = knn_model.predict ( X_train)
y_pred_train [:5]

array([0., 1., 0., 0., 0.])

In [ ]:
y_test[100:106]

894     1
107     1
881     1
1010    0
299     0
548     0
Name: diagnosis_Diagnosed, dtype: int64

In [ ]:
y_pred_test = knn_model.predict( X_test )

In [ ]:
y_pred_test [100:106]

array([1., 1., 1., 0., 0., 0.])

In [ ]:
pd.DataFrame({
    'Actural': y_test[100:110],
    'Predicted': y_pred_test[100:110],
    'Residuals': y_test[100:110] - y_pred_test [100:110]
})

      Actural  Predicted  Residuals
894         1        1.0        0.0
107         1        1.0        0.0
881         1        1.0        0.0
1010        0        0.0        0.0
299         0        0.0        0.0
548         0        0.0        0.0
1002        0        0.0        0.0
929         1        1.0        0.0
342         0        0.0        0.0
714         0        0.0        0.0

## Metrics
- MAE = mean absolute error
- MSE = mean squared error
- RMSE = root mean squared error

In [ ]:
MAE_train = mean_absolute_error ( y_train, y_pred_train)
MAE_test = mean_absolute_error ( y_test, y_pred_test)

MSE_train = mean_squared_error ( y_train, y_pred_train )
MSE_test = mean_squared_error ( y_test, y_pred_test)

RMSE_train = root_mean_squared_error ( y_train, y_pred_train)
RMSE_test = root_mean_squared_error ( y_test, y_pred_test)

print( f'Mean absolute error of training:  {MAE_train}')
print( f'Mean absolute error of testing {MAE_test}')

print( )
print( f'Mean squared error of training {MSE_train}')
print( f'Mean squared error of testing {MSE_test}')

print( )
print( f'Root mean squared error of training {RMSE_train}')
print( f'Root mean squred error of training {RMSE_test}')

Mean absolute error of training:  0.0
Mean absolute error of testing 0.01951219512195122

Mean squared error of training 0.0
Mean squared error of testing 0.01951219512195122

Root mean squared error of training 0.0
Root mean squred error of training 0.13968605915391563

In [ ]:
cross_val_score ( knn_model, X_train, y_train, cv= 4, scoring='neg_root_mean_squared_error').mean()

np.float64(-0.24829072839021865)

Testing GridSearchCV on KNN Model

In [ ]:
knn_model = KNeighborsRegressor( )

In [ ]:
gs_knn = GridSearchCV(
    estimator= knn_model, 
    param_grid= { 'n_neighbors': [ 2, 3, 4, 5, 6, 7]}
)

In [ ]:
gs_knn.fit( X_train, y_train)

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7]})

In [ ]:
gs_knn.best_params_

{'n_neighbors': 2}

In [ ]:
knn_comparion_df = pd.DataFrame({
    'Actual ( True )': y_test,
    'Predicted ( KNN )': y_pred_test,
    'Residuals':  np.abs( y_test - y_pred_test)
}) 

knn_comparion_df

     Actual ( True )  Predicted ( KNN )  Residuals
525                1                1.0        0.0
357                1                1.0        0.0
444                0                0.0        0.0
31                 0                0.0        0.0
618                1                1.0        0.0
..               ...                ...        ...
542                1                1.0        0.0
903                0                0.0        0.0
528                0                0.0        0.0
294                1                1.0        0.0
745                1                1.0        0.0

[205 rows x 3 columns]

In [ ]:
knn_comparion_df.head(10)

     Actual ( True )  Predicted ( KNN )  Residuals
525                1                1.0        0.0
357                1                1.0        0.0
444                0                0.0        0.0
31                 0                0.0        0.0
618                1                1.0        0.0
587                1                1.0        0.0
447                0                0.0        0.0
734                0                0.0        0.0
76                 0                0.0        0.0
715                1                1.0        0.0

# [2] Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg_model = LinearRegression()

In [ ]:
lin_reg_model.fit( X_train, y_train)

LinearRegression()

In [ ]:
y_pred_train_lr = lin_reg_model.predict( X_train)
y_pred_test_lr = lin_reg_model.predict( X_test )

In [ ]:
y_pred_train_lr

array([ 3.12856080e-01,  6.78350436e-01,  1.83744157e-01, -6.52455561e-04,
        1.97312469e-01,  1.27285814e-01,  2.66931103e-01, -6.06402707e-02,
        1.91533615e-01,  7.96164995e-01,  9.80806189e-01,  5.16785214e-01,
        8.04122311e-01,  1.17785010e+00,  2.12743158e-01,  8.91669300e-01,
        4.02553906e-03,  9.01565830e-01,  1.12485435e+00,  4.47328648e-01,
        3.07910931e-02,  1.02691455e+00,  3.92231143e-01,  3.30866949e-01,
        3.18573261e-01,  4.14443176e-01,  3.42153347e-01,  7.37489116e-01,
        6.38574323e-01,  9.49473444e-01,  1.10015519e+00,  4.10459234e-01,
        6.29932736e-01,  9.01565830e-01,  6.15273065e-01,  7.43294294e-01,
        8.35261926e-01,  1.16899053e-01,  4.13152395e-01,  1.01474858e-02,
        5.66163150e-01,  3.92582709e-01,  8.25120337e-01,  6.29932736e-01,
        8.44254179e-01,  6.78350436e-01,  1.59499246e-01,  1.44938865e-01,
        1.65476099e-01,  2.61815166e-01,  7.19185233e-01,  2.79044230e-01,
        9.72806360e-01,  1.02567047e+00,  5.45358052e-01,  3.13688970e-01,
        6.26413348e-01,  5.86213803e-01,  7.20797783e-01,  1.04167125e+00,
       -9.75778015e-02,  2.21492732e-01,  5.88520966e-01,  6.69233807e-02,
        4.28240717e-01,  6.09724186e-01, -2.05548070e-02,  6.26016902e-01,
       -1.62521903e-01,  6.78350436e-01,  3.63070252e-01,  1.70485337e-01,
        5.29457287e-01,  1.15665068e+00,  3.07910931e-02,  6.08801100e-01,
        7.85803920e-01,  4.02553906e-03,  1.15665068e+00,  5.23101296e-01,
        2.49759864e-01,  1.10015519e+00,  5.71705054e-01,  6.26016902e-01,
        1.04063698e-01,  3.96977890e-03,  1.65476099e-01,  8.31196205e-01,
        7.09124413e-02,  1.19930308e+00,  1.08881968e+00,  4.92018969e-01,
        8.41467238e-01,  5.71705054e-01,  3.88067627e-01,  8.89279113e-01,
       -1.92048645e-02,  4.47746752e-01,  1.03936850e+00,  9.13179003e-01,
        6.88698048e-02,  9.12672571e-01,  2.00002114e-01,  2.21492732e-01,
       -8.65472485e-02,  3.67681550e-01,  6.48452124e-01,  8.96274603e-01,
       -1.26210590e-01,  3.83279655e-01,  5.22636566e-01, -1.92048645e-02,
        1.44938865e-01,  9.78272420e-01,  2.45292044e-01,  1.91045653e-01,
        1.01474858e-02,  5.00815064e-01,  2.07729845e-01,  8.66667296e-01,
        1.08399106e-01,  7.84806048e-01,  7.13970555e-01,  1.91085800e-01,
        9.16007579e-01,  2.32131040e-01,  3.10737553e-01, -1.41972443e-03,
        8.31196205e-01,  6.48452124e-01,  1.35376080e+00,  3.53095445e-02,
        2.89318682e-01,  8.25120337e-01,  8.70989755e-01,  2.12743158e-01,
        3.92231143e-01, -1.68029801e-02,  6.09724186e-01, -2.05548070e-02,
        1.16052531e-01,  8.66667296e-01,  5.46295687e-01,  2.61815166e-01,
        1.46903845e-01,  1.44068776e-02,  8.41467238e-01,  1.95037836e-01,
        6.16178774e-01,  4.91508516e-01,  6.32387966e-01,  2.37588851e-01,
        7.99743671e-01,  7.09054171e-01,  1.44938865e-01,  2.52021549e-01,
        3.72998244e-01,  3.46910646e-01,  1.30370461e-01, -1.80401254e-01,
        3.45663642e-01,  7.64717880e-01,  4.13539767e-01,  3.67681550e-01,
       -2.05548070e-02,  3.63070252e-01,  3.93193216e-01,  1.12881198e-01,
        4.16873366e-01,  5.46295687e-01,  1.02240258e+00,  1.17974702e+00,
        7.30896639e-02, -2.25346054e-01,  1.95281232e-02,  7.38624149e-01,
        2.79044230e-01,  1.06229410e+00,  3.95230844e-01,  7.94325574e-01,
        6.94198356e-01,  8.45502162e-02,  8.23442014e-01,  5.61889279e-01,
        1.07552217e+00,  4.16580265e-01,  7.99711697e-01,  1.04063698e-01,
        1.13276744e-01, -2.31170782e-02,  2.99771213e-02,  1.06568798e+00,
       -1.62521903e-01,  9.95501735e-01,  5.76537993e-01,  1.09631124e+00,
        2.92128343e-01,  6.08801100e-01,  4.04511314e-01,  9.01565830e-01,
        8.25120337e-01,  8.79062695e-01,  2.92128343e-01,  6.88698048e-02,
        1.12881198e-01,  6.32387966e-01,  7.66296788e-01,  1.26967910e-01,
        1.19930308e+00,  1.13280297e+00,  1.75531370e-01,  1.15312576e+00,
        5.65356737e-01,  6.47297128e-01,  3.90213044e-01,  5.76537993e-01,
        3.83279655e-01,  4.13152395e-01,  1.15781038e+00,  9.17545663e-01,
        5.05724994e-01,  3.49981780e-02,  1.92394099e-01,  1.17974702e+00,
        1.07552217e+00,  4.23708593e-01, -2.31170782e-02,  8.44254179e-01,
        7.66296788e-01,  5.71313295e-01,  6.09982736e-01,  7.85803920e-01,
        1.16899053e-01,  1.12596037e+00,  6.94198356e-01,  8.32811156e-01,
        1.45607458e-01,  3.20055257e-01,  8.74609008e-01,  3.42153347e-01,
        6.15273065e-01, -9.04756500e-02,  4.13539767e-01,  8.91669300e-01,
        9.83526547e-01,  7.99711697e-01,  6.47297128e-01,  5.00815064e-01,
        3.13688970e-01,  4.91508516e-01,  1.13276744e-01,  2.00002114e-01,
        8.89981000e-01,  3.93873028e-01,  1.16052531e-01,  9.78272420e-01,
       -2.12872047e-01,  9.01565830e-01,  2.36883828e-01,  3.27264559e-01,
        1.13280297e+00, -1.62521903e-01,  1.08881968e+00,  5.61889279e-01,
        6.48452124e-01,  2.80124897e-01,  5.10881844e-02,  5.72669866e-01,
        7.20797783e-01,  9.54451964e-01,  9.16007579e-01,  8.70989755e-01,
       -1.41972443e-03,  1.13276744e-01,  4.16837879e-01,  1.13639195e+00,
        6.39943565e-01,  1.13276744e-01,  1.19930308e+00,  8.96274603e-01,
        6.48452124e-01,  1.94101143e-01,  1.07552217e+00,  8.41467238e-01,
        1.02609942e+00,  7.94325574e-01,  2.34284719e-01,  3.86137826e-01,
       -8.65472485e-02,  4.84814404e-01,  2.99771213e-02,  2.65174144e-01,
        3.74404900e-01, -1.26210590e-01,  1.04167125e+00,  1.13639195e+00,
        1.03197424e+00,  4.69089417e-01,  9.95501735e-01,  9.98682867e-02,
        8.89981000e-01,  1.03936850e+00,  5.10690417e-01,  3.83874392e-01,
        3.92582709e-01,  1.91045653e-01,  8.32811156e-01,  8.79062695e-01,
        7.03281374e-02,  1.44938865e-01,  2.60830195e-01,  5.44232266e-01,
        4.98028851e-01,  2.32131040e-01,  6.29932736e-01,  8.89981000e-01,
        5.76537993e-01,  3.86137826e-01,  3.12856080e-01,  3.94086784e-01,
       -2.12872047e-01,  1.01474858e-02,  1.91533615e-01,  3.27264559e-01,
        3.93193216e-01,  9.42487925e-01,  9.32267342e-02,  8.58362227e-02,
        7.37489116e-01,  1.15781038e+00,  7.30896639e-02,  2.47458333e-01,
        1.36370558e-01,  6.70083571e-02, -1.17025311e-01,  1.13280297e+00,
        4.13152395e-01,  8.71047280e-01,  4.82123955e-01,  4.44408989e-01,
       -9.75778015e-02,  4.02553906e-03,  7.20797783e-01,  9.49473444e-01,
        2.60830195e-01,  5.65356737e-01,  2.59248103e-01,  1.06919946e+00,
        9.78272420e-01,  8.35261926e-01,  1.91085800e-01,  5.71705054e-01,
        1.86271792e-01,  9.16007579e-01,  3.83874392e-01,  7.55836809e-01,
        6.69233807e-02, -3.56593344e-02,  5.45358052e-01,  8.35261926e-01,
        3.10737553e-01,  2.34284719e-01,  2.39695913e-01,  2.37194589e-01,
        1.95281232e-02,  8.32811156e-01,  7.20797783e-01,  1.26967910e-01,
        5.45358052e-01,  3.29986444e-01,  8.08215189e-01,  3.92582709e-01,
        3.86137826e-01,  3.69532636e-01, -1.68029801e-02,  1.44301749e-01,
       -1.41972443e-03,  1.16899053e-01,  9.20614888e-02,  4.60226282e-01,
        8.25120337e-01,  2.37194589e-01,  1.03936850e+00,  1.75531370e-01,
        7.19185233e-01, -4.84517125e-02,  2.92128343e-01,  5.05724994e-01,
        5.10690417e-01,  2.37588851e-01,  8.73617959e-01,  3.18573261e-01,
        3.96037147e-02,  2.49759864e-01,  1.08181463e+00,  1.59499246e-01,
        2.70836671e-01,  3.93873028e-01,  5.46295687e-01,  4.16873366e-01,
        9.30093339e-01,  1.09631124e+00,  5.10881844e-02, -4.84517125e-02,
        1.06229410e+00,  1.12596037e+00,  8.08215189e-01,  1.13639195e+00,
        1.56047288e-01,  6.47297128e-01,  1.44068776e-02,  2.56089668e-01,
        1.08181463e+00,  4.08206842e-01,  6.26413348e-01,  4.37832786e-01,
        6.39943565e-01,  1.56047288e-01,  1.15592798e-01,  6.62828697e-01,
        6.32387966e-01,  6.34702337e-01,  1.04167125e+00,  4.91508516e-01,
        2.03886536e-01,  3.46910646e-01,  1.13639195e+00,  1.08181463e+00,
        8.74609008e-01,  8.73617959e-01,  3.90213044e-01,  2.41826872e-01,
        1.11104175e+00,  5.65356737e-01, -4.84517125e-02,  9.54451964e-01,
        2.89318682e-01,  4.44408989e-01,  3.13688970e-01,  9.42487925e-01,
        3.46910646e-01,  1.11104175e+00,  4.91508516e-01,  1.06229410e+00,
        3.93193216e-01,  1.13280297e+00,  2.39695913e-01,  4.80110047e-01,
        2.70836671e-01,  1.83744157e-01,  1.44301749e-01,  5.29457287e-01,
        5.23101296e-01,  7.92782980e-01,  3.12189231e-01,  7.46121938e-02,
        4.16873366e-01, -1.80401254e-01,  9.09354931e-02,  3.96037147e-02,
        8.58362227e-02,  6.70083571e-02,  1.15781038e+00,  1.75531370e-01,
        8.44254179e-01,  1.70485337e-01,  9.12672571e-01,  3.95230844e-01,
        1.97312469e-01,  1.19101516e+00,  7.69492486e-01,  2.07729845e-01,
        6.69201023e-01,  4.10459234e-01,  1.45607458e-01,  3.96037147e-02,
        7.09054171e-01,  5.71705054e-01,  6.48705747e-01,  2.59248103e-01,
        2.60830195e-01,  2.43008802e-01,  1.97312469e-01,  7.84806048e-01,
        4.60226282e-01,  5.65356737e-01,  9.32267342e-02,  8.73617959e-01,
        3.98705923e-01,  8.45317803e-01,  9.14055376e-02,  1.15592798e-01,
        3.12189231e-01,  9.17545663e-01,  9.17545663e-01,  5.46295687e-01,
        6.48705747e-01,  3.83874392e-01,  1.95281232e-02,  1.27285814e-01,
        1.15312576e+00,  1.17785010e+00,  1.02609942e+00, -5.87942630e-02,
        6.26016902e-01, -1.80401254e-01,  6.69201023e-01,  2.47541043e-01,
        8.71047280e-01,  7.96164995e-01, -6.06402707e-02,  9.95501735e-01,
        2.70836671e-01,  9.42487925e-01,  8.55552558e-01,  1.08881968e+00,
        8.79062695e-01,  6.16178774e-01,  7.99743671e-01,  4.04511314e-01,
        7.03281374e-02,  6.53594836e-01,  4.01280448e-01, -2.25346054e-01,
        9.49473444e-01,  5.72669866e-01,  5.66163150e-01,  3.98705923e-01,
        8.79062695e-01,  3.15133053e-01,  3.20055257e-01,  8.91669300e-01,
       -5.87942630e-02,  9.30093339e-01,  2.61815166e-01,  8.32811156e-01,
       -1.26210590e-01,  3.29986444e-01,  3.05773615e-01,  1.17785010e+00,
        1.65476099e-01,  3.92231143e-01,  3.95230844e-01,  3.98705923e-01,
        4.69089417e-01,  6.38574323e-01,  4.80110047e-01,  7.55836809e-01,
        1.35376080e+00, -9.04756500e-02,  3.20055257e-01,  3.92582709e-01,
       -2.25346054e-01,  3.46910646e-01,  7.39271811e-01,  9.12672571e-01,
        5.33684129e-01,  1.08881968e+00,  9.30093339e-01,  1.30370461e-01,
        4.01280448e-01,  1.65476099e-01,  5.71313295e-01,  9.80806189e-01,
        3.18573261e-01, -2.12872047e-01,  7.69492486e-01,  8.08215189e-01,
        1.86271792e-01,  6.78350436e-01,  6.53594836e-01,  1.06568798e+00,
        2.47458333e-01,  8.41467238e-01,  8.89279113e-01,  1.04305331e+00,
        1.06229410e+00,  7.13970555e-01,  5.11955083e-01,  2.65174144e-01,
        2.49759864e-01,  4.14443176e-01, -1.17025311e-01,  2.80124897e-01,
        8.35261926e-01, -6.52455561e-04,  4.51101852e-02,  8.23442014e-01,
        2.03886536e-01,  2.56089668e-01,  2.37078396e-01,  5.33684129e-01,
        4.98028851e-01,  9.98682867e-02,  9.49473444e-01, -6.06402707e-02,
        6.41410084e-01,  2.36883828e-01,  4.12272597e-01,  3.53095445e-02,
        6.34702337e-01,  4.53589863e-01,  1.19101516e+00,  1.03936850e+00,
        3.93873028e-01,  3.10737553e-01,  4.14443176e-01,  1.15781038e+00,
        8.88093675e-01,  1.06568798e+00,  1.11104175e+00,  3.67681550e-01,
        1.70485337e-01,  1.15592798e-01,  2.47541043e-01,  2.73066957e-01,
        4.37832786e-01,  1.26967910e-01,  3.07910931e-02,  5.00815064e-01,
        6.09982736e-01, -3.56593344e-02,  7.30896639e-02,  5.88520966e-01,
        1.92394099e-01,  3.74404900e-01,  6.40678461e-02,  5.98053282e-01,
        7.09124413e-02,  6.40678461e-02,  1.17974702e+00,  6.15273065e-01,
        4.01280448e-01,  7.64717880e-01,  1.86271792e-01,  7.91516676e-01,
        3.74404900e-01,  1.45607458e-01,  3.69532636e-01,  4.92018969e-01,
        5.72669866e-01,  4.84814404e-01,  1.02240258e+00,  1.91045653e-01,
        4.16873366e-01,  1.03197424e+00,  1.30370461e-01, -3.56593344e-02,
        8.04122311e-01,  2.00002114e-01,  4.47328648e-01,  1.44301749e-01,
        1.06919946e+00,  6.38574323e-01,  2.73066957e-01,  6.39943565e-01,
        5.47258650e-01,  4.03304291e-01,  7.09054171e-01,  1.12485435e+00,
        1.04305331e+00,  4.92018969e-01,  4.51101852e-02,  7.92782980e-01,
        8.88093675e-01,  4.82123955e-01,  8.44254179e-01,  2.99771213e-02,
        2.45292044e-01,  2.07729845e-01,  5.10690417e-01,  6.69201023e-01,
        2.43008802e-01,  8.66667296e-01, -8.65472485e-02, -1.92048645e-02,
        1.95037836e-01,  4.92018969e-01,  2.36883828e-01,  5.86213803e-01,
        2.65174144e-01,  2.59248103e-01,  9.13179003e-01,  2.80124897e-01,
        3.05773615e-01,  5.44232266e-01,  2.41826872e-01,  7.91516676e-01,
        4.12272597e-01,  2.47458333e-01,  3.96977890e-03,  8.89279113e-01,
        6.15273065e-01,  2.66931103e-01,  1.95037836e-01,  9.83526547e-01,
        9.17545663e-01,  8.23442014e-01,  1.04167125e+00,  9.72806360e-01,
        1.03197424e+00,  5.00815064e-01,  3.12189231e-01,  5.61889279e-01,
        7.91516676e-01,  2.61991120e-01,  7.85803920e-01,  9.13179003e-01,
        1.56047288e-01, -2.31170782e-02,  2.56089668e-01, -8.65472485e-02,
        1.70485337e-01,  1.04305331e+00,  2.15947480e-01,  6.32387966e-01,
        2.00002114e-01, -5.87942630e-02,  4.98028851e-01,  6.08801100e-01,
        3.07910931e-02,  2.15947480e-01,  5.16785214e-01,  6.48705747e-01,
        7.66296788e-01,  4.47746752e-01,  8.31196205e-01,  9.09354931e-02,
        2.07729845e-01,  8.89279113e-01,  9.98682867e-02,  3.83279655e-01,
        3.49981780e-02,  2.89318682e-01,  5.98053282e-01,  2.52021549e-01,
        1.46903845e-01,  4.47328648e-01,  6.62828697e-01,  8.91669300e-01,
        1.19101516e+00,  4.16580265e-01,  3.10737553e-01,  2.99771213e-02,
        5.00815064e-01,  3.45663642e-01,  1.16052531e-01,  8.70989755e-01,
        1.15665068e+00,  6.03710580e-01,  1.35376080e+00,  2.52021549e-01,
        1.12485435e+00,  8.96274603e-01,  7.55836809e-01,  7.64717880e-01,
        6.30186875e-02,  1.15665068e+00,  6.41410084e-01,  6.94198356e-01,
        7.39271811e-01,  8.71047280e-01,  2.21492732e-01,  5.11955083e-01,
        5.47258650e-01,  4.53589863e-01,  8.45317803e-01,  4.44408989e-01,
        1.10015519e+00,  6.69201023e-01,  3.15133053e-01,  7.94325574e-01,
        1.30370461e-01,  5.86213803e-01,  4.53589863e-01,  1.15312576e+00,
        7.84806048e-01,  9.16007579e-01,  6.03710580e-01,  3.94086784e-01,
        9.20614888e-02,  4.60226282e-01,  1.36370558e-01,  9.83526547e-01,
        2.73066957e-01,  2.34284719e-01,  9.80806189e-01,  7.69492486e-01,
        5.05724994e-01,  6.88698048e-02,  2.56089668e-01,  3.49981780e-02,
        7.38624149e-01,  4.14443176e-01,  7.94325574e-01, -3.56593344e-02,
        1.26967910e-01,  4.84814404e-01,  2.79044230e-01, -1.80401254e-01,
        1.27285814e-01,  4.13152395e-01,  4.16837879e-01,  3.95230844e-01,
        4.23708593e-01,  4.12272597e-01,  5.86213803e-01,  1.43367749e-01,
        8.31196205e-01,  4.82123955e-01,  1.74542887e-01,  5.47258650e-01,
        7.99743671e-01,  8.45317803e-01,  6.53594836e-01,  3.72998244e-01,
        2.61991120e-01,  4.23708593e-01,  2.45292044e-01])

In [ ]:
y_train

137    0
377    1
388    0
824    0
767    0
      ..
106    1
270    0
860    1
435    1
102    0
Name: diagnosis_Diagnosed, Length: 819, dtype: int64

In [ ]:
lin_reg_model.intercept_

np.float64(-0.028475342716918317)

In [ ]:
X_train.shape

(819, 20)

In [ ]:
lin_reg_model.coef_

array([ 0.00039508,  0.09969262,  0.00136367,  0.00059744, -0.00230218,
        0.05992307,  0.09548682,  0.14151112, -0.11115436,  0.11115436,
        0.0158203 , -0.0158203 , -0.06662007,  0.0845431 , -0.01792303,
       -0.07389304,  0.06719875,  0.00669429, -0.05784992,  0.05784992])

In [ ]:
print( 'Linear Regression Wvaluation :')
print(35* '--')
print( )
MAE_train = mean_absolute_error ( y_train, y_pred_train_lr)
MAE_test = mean_absolute_error ( y_test, y_pred_test_lr)

MSE_train = mean_squared_error ( y_train, y_pred_train_lr )
MSE_test = mean_squared_error ( y_test, y_pred_test_lr)

RMSE_train = root_mean_squared_error ( y_train, y_pred_train_lr)
RMSE_test = root_mean_squared_error ( y_test, y_pred_test_lr)

print( f'Mean absolute error of training:  {MAE_train}')
print( f'Mean absolute error of testing {MAE_test}')

print( )
print( f'Mean squared error of training {MSE_train}')
print( f'Mean squared error of testing {MSE_test}')

print( )
print( f'Root mean squared error of training {RMSE_train}')
print( f'Root mean squred error of training {RMSE_test}')

Linear Regression Wvaluation :
----------------------------------------------------------------------

Mean absolute error of training:  0.27847996124112007
Mean absolute error of testing 0.2805702197276905

Mean squared error of training 0.12166319741327589
Mean squared error of testing 0.12464246027415576

Root mean squared error of training 0.34880251921864885
Root mean squred error of training 0.35304739097486015

# Define a functin to evaluate any regressor

In [ ]:
def evaluate_regressor( model, model_name: str, X_train, X_test, y_trin, y_test):

    print( 'Training name:' + 41 * '-' + '\n')

    print( model_name + ':')
    print( '-' * 55)

    model.fit( X_train, y_train )
    y_pred_train = model.predict( X_train )
    y_pred_test = model.predict ( X_test )

    print( )

    MAE_train = mean_absolute_error( y_train, y_pred_train )
    MSE_train = mean_squared_error( y_train, y_pred_train )
    RMSE_train = root_mean_squared_error( y_train, y_pred_train )
    
    MAE_test = mean_absolute_error( y_test, y_pred_test )
    MSE_test = mean_squared_error( y_test, y_pred_test )
    RMSE_test = root_mean_squared_error( y_test, y_pred_test )

    print( f'Mean Absolute Error of training : { MAE_train }' )
    print( Fore.CYAN + f'Mean Squared Error of training : { MSE_train }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Training : { RMSE_train }' )
    print(  )

    print( Fore.WHITE + f'Mean Absolute Error of Testing : { MAE_test }' )
    print( Fore.RED  + f'Mean Squared Error of Testing : { MSE_test }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Testing : { RMSE_test }' )

# [1] KNN

In [ ]:
knn_model = KNeighborsRegressor( n_neighbors= 7 )

In [ ]:
evaluate_regressor( knn_model, 'K Neighbors Regressor', X_train, X_test, y_train, y_test)

Training name:-----------------------------------------

K Neighbors Regressor:
-------------------------------------------------------

Mean Absolute Error of training : 0.25065410779696495
Mean Squared Error of training : 0.12167650943161147
Root Mean Squared Error of Training : 0.3488216011539587

Mean Absolute Error of Testing : 0.28432055749128915
Mean Squared Error of Testing : 0.15788949726231957
Root Mean Squared Error of Testing : 0.39735311407150137

# [2] Linear Regression

In [ ]:
lin_reg_model = LinearRegression()

In [ ]:
evaluate_regressor( lin_reg_model, 'Linear Regression without regularizaion', X_train, X_test, y_train, y_test)

Training name:-----------------------------------------

Linear Regression without regularizaion:
-------------------------------------------------------

Mean Absolute Error of training : 0.27847996124112007
Mean Squared Error of training : 0.12166319741327589
Root Mean Squared Error of Training : 0.34880251921864885

Mean Absolute Error of Testing : 0.2805702197276905
Mean Squared Error of Testing : 0.12464246027415576
Root Mean Squared Error of Testing : 0.35304739097486015

# [3] Linear Regression with regularization L1 (Lasso )

In [ ]:
lin_reg_L1 = Lasso ( alpha = 0.2 )

In [ ]:
evaluate_regressor (  lin_reg_L1, 'Linear Regression with Regularizaion ( L1 )', X_train, X_test, y_train, y_test)

Training name:-----------------------------------------

Linear Regression with Regularizaion ( L1 ):
-------------------------------------------------------

Mean Absolute Error of training : 0.4107384481377937
Mean Squared Error of training : 0.20211096907293347
Root Mean Squared Error of Training : 0.44956753560831486

Mean Absolute Error of Testing : 0.3968138802982935
Mean Squared Error of Testing : 0.19346643093458094
Root Mean Squared Error of Testing : 0.43984819078243453

## [4] Linear Regression with regularization L2 ( Ridge )
- Dieser Befehl erstellt ein Ridge-Regressionsmodell, das auch als L2-Regularisierung bekannt ist.
- Genau wie Lasso hilft Ridge dabei, Overfitting (Überanpassung) zu verhindern, nutzt dafür aber eine andere mathematische Methode.
#### Das passiert im Hintergrund:
- Bestrafung grosser Gewichte: Ridge fügt der Fehlerberechnung eine Strafe hinzu, die auf den Quadraten der Koeffizienten basiert.
- Schrumpfung (Shrinkage): Das Modell versucht, die Koeffizienten so klein wie möglich zu halten, damit kein einzelnes Merkmal die Vorhersage zu extrem dominiert.
- Der grosse Unterschied zu Lasso: Ridge setzt Koeffizienten fast nie exakt auf Null. Es behält alle Merkmale im Modell, schwächt die unwichtigen aber extrem stark ab.

In [ ]:
ridge = Ridge( )

In [ ]:
evaluate_regressor ( ridge, 'Linear Regression with Regularizaion ( L2 )', X_train, X_test, y_train, y_test)

Training name:-----------------------------------------

Linear Regression with Regularizaion ( L2 ):
-------------------------------------------------------

Mean Absolute Error of training : 0.27861758714402446
Mean Squared Error of training : 0.12166419909911758
Root Mean Squared Error of Training : 0.34880395510819195

Mean Absolute Error of Testing : 0.2806924728939031
Mean Squared Error of Testing : 0.12461249813901538
Root Mean Squared Error of Testing : 0.3530049548363527

# [5] Support verctor machine

In [ ]:
from sklearn.svm import SVR

In [ ]:
svm_regressor = SVR( )

In [ ]:
evaluate_regressor( svm_regressor, 'SVM', X_train, X_test, y_train, y_test)

Training name:-----------------------------------------

SVM:
-------------------------------------------------------

Mean Absolute Error of training : 0.37834551500449937
Mean Squared Error of training : 0.20073535364228817
Root Mean Squared Error of Training : 0.448034991537813

Mean Absolute Error of Testing : 0.36174920278500966
Mean Squared Error of Testing : 0.19637043562116963
Root Mean Squared Error of Testing : 0.44313703932437154

# [6] Support Vector machine with Scaling ( SVM )

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
svm_pipeline = make_pipeline(
    StandardScaler(),
    svm_regressor
)

In [ ]:
svm_pipeline

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [ ]:
evaluate_regressor( svm_pipeline, 'SVM with Scaling', X_train, X_test, y_train, y_test)

Training name:-----------------------------------------

SVM with Scaling:
-------------------------------------------------------

Mean Absolute Error of training : 0.12172246634726455
Mean Squared Error of training : 0.03289763718340559
Root Mean Squared Error of Training : 0.18137705804044124

Mean Absolute Error of Testing : 0.13233537984303526
Mean Squared Error of Testing : 0.03945135753826874
Root Mean Squared Error of Testing : 0.19862365805278268

In [ ]:
joblib.dump( svm_pipeline, '../ml_Session_23_Task_Heart-Disease-Patients-Records/artifacts/svm_pipeline.pkl')

['../ml_Session_23_Task_Heart-Disease-Patients-Records/artifacts/svm_pipeline.pkl']