In [23]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from colorama import Fore

# Preprocessing Essentials
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import make_pipeline, Pipeline
# Google nach: für Standard Scaler formula

# Regressors
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR

# Evaluation Metrics
from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [24]:
os.listdir()

['artifacts',
 'data',
 'EDA.ipynb',
 'machine-learning_2.ipynb',
 'machine_learning_1.ipynb',
 'pre-processing.ipynb',
 'Task.py',
 'Virtualazation.ipynb']

In [25]:
df = pd.read_csv('../ml_Session_23_Task_Heart-Disease-Patients-Records/data/preprocessed-data/preprocessed-data.csv')

In [26]:
df.sample(3)

,age,chest_pain_type,resisting_blood_pressure,cholesterol_level,max_heart_rate_achieved,st_depression,num_major_vessels,thalassemia,sex_female,sex_male,...,rest_ecg_ST-T wave abnormality,rest_ecg_left ventricular hypertrophy,rest_ecg_normal,diagnosis_Diagnosed,diagnosis_Un-Diagnosed,st_slope_downsloping,st_slope_flat,st_slope_upsloping,exercise_induced_angina_no,exercise_induced_angina_yes
206,59,2,126,218,134,2.2,1,0,0,1,...,1,0,0,1,0,0,1,0,1,0
587,61,3,145,307,146,1.0,0,2,1,0,...,0,0,1,1,0,0,1,0,0,1
553,58,3,100,234,156,0.1,1,2,0,1,...,1,0,0,1,0,1,0,0,1,0

# Split features into X and y

## Die sicherere Lösung für deinen Code:
Damit dein Modell wirklich medizinisch lernt, solltest du beide Diagnose-Spalten aus X entfernen:

In [27]:
# Wir löschen BEIDE Diagnose-Spalten aus X
X = df.drop( columns= ['diagnosis_Diagnosed', 'diagnosis_Un-Diagnosed'])

# Und setzen eine davon als unser Ziel y
y = df["diagnosis_Diagnosed"]

In [28]:
X.shape

(1024, 20)

# Split into training and testing

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state= 42)

In [30]:
X_train

,age,chest_pain_type,resisting_blood_pressure,cholesterol_level,max_heart_rate_achieved,st_depression,num_major_vessels,thalassemia,sex_female,sex_male,fasting_blood_sugar_higher than 120mg/ml,fasting_blood_sugar_lower than 120mg/ml,rest_ecg_ST-T wave abnormality,rest_ecg_left ventricular hypertrophy,rest_ecg_normal,st_slope_downsloping,st_slope_flat,st_slope_upsloping,exercise_induced_angina_no,exercise_induced_angina_yes
137,64,3,180,325,154,0.0,0,1,1,0,0,1,1,0,0,1,0,0,0,1
377,67,3,120,237,71,1.0,0,1,0,1,0,1,1,0,0,0,1,0,1,0
388,63,0,145,233,150,2.3,0,0,0,1,1,0,0,0,1,0,0,1,1,0
824,63,2,135,252,172,0.0,0,1,1,0,0,1,0,0,1,1,0,0,1,0
767,46,1,101,197,156,0.0,0,2,0,1,1,0,1,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,51,3,140,299,173,1.6,0,2,0,1,0,1,1,0,0,1,0,0,0,1
270,43,3,110,211,161,0.0,0,2,0,1,0,1,1,0,0,1,0,0,1,0
860,64,2,140,335,158,0.0,0,1,0,1,0,1,1,0,0,1,0,0,1,0
435,59,3,174,249,143,0.0,0,1,1,0,0,1,1,0,0,0,1,0,0,1
102,54,1,108,309,156,0.0,0,2,0,1,0,1,1,0,0,1,0,0,1,0

# Model Selection
## Getting Your Preproccing Pipeline ready !

In [31]:
df.columns

Index(['age', 'chest_pain_type', 'resisting_blood_pressure',
       'cholesterol_level', 'max_heart_rate_achieved', 'st_depression',
       'num_major_vessels', 'thalassemia', 'sex_female', 'sex_male',
       'fasting_blood_sugar_higher than 120mg/ml',
       'fasting_blood_sugar_lower than 120mg/ml',
       'rest_ecg_ST-T wave abnormality',
       'rest_ecg_left ventricular hypertrophy', 'rest_ecg_normal',
       'diagnosis_Diagnosed', 'diagnosis_Un-Diagnosed', 'st_slope_downsloping',
       'st_slope_flat', 'st_slope_upsloping', 'exercise_induced_angina_no',
       'exercise_induced_angina_yes'],
      dtype='object')

In [32]:
preprocessing_step = ColumnTransformer([
    ( 'One-Hot Encoding', OneHotEncoder(), [ 'sex','fasting_blood_sugar', 'rest_ecg', 'diagnosis', 'st_slope', 'exercise_induced_angina' ]),

], remainder = 'passthtrough' )

preprocessing_step

ColumnTransformer(remainder='passthtrough',
                  transformers=[('One-Hot Encoding', OneHotEncoder(),
                                 ['sex', 'fasting_blood_sugar', 'rest_ecg',
                                  'diagnosis', 'st_slope',
                                  'exercise_induced_angina'])])

In [33]:
knn_model = KNeighborsRegressor( n_neighbors= 7  )

In [37]:
knn_Pipeline = Pipeline([
    ( 'One-Hor Encoding', preprocessing_step),
    (  'model', knn_model )
])

knn_Pipeline

Pipeline(steps=[('One-Hor Encoding',
                 ColumnTransformer(remainder='passthtrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['sex', 'fasting_blood_sugar',
                                                   'rest_ecg', 'diagnosis',
                                                   'st_slope',
                                                   'exercise_induced_angina'])])),
                ('model', KNeighborsRegressor(n_neighbors=7))])

Define a function to quickly evaluate your regressor !

In [35]:
def evaluate_regressor ( model, model_name: str , X_train, X_test, y_train, y_test):

    print( 'Training'+ 35 * "_" + '\n' )

    print( model_name + ':')
    print( '_' * 40 )

    model.fit( X_train, y_train )
    y_pred_train = model.predict ( X_train )
    y_pred_test = model.predict( X_test )

    print( )

    MAE_train = mean_absolute_error ( y_train, y_pred_train )
    MSE_train = mean_squared_error ( y_train, y_pred_train )
    RMSE_train = root_mean_squared_error( y_train, y_pred_test )

    MAE_test = mean_absolute_error ( y_test, y_pred_test )
    MSE_test = mean_squared_error ( y_test, y_pred_test )
    RMSE_test = root_mean_squared_error ( y_test, y_pred_test )

    print( f'Mean absolute error of training: {MAE_train}' )
    print( Fore.CYAN + f'Mean squared error of training: {MSE_train}' )
    print( Fore.WHITE + f'Root mean squared error of training: {RMSE_train}' )
    print( )

    print( Fore.WHITE + f'Mean absolute error of testing: {MAE_test}' )
    print( Fore.CYAN + f'Mean squared error of testing: {MSE_test}' )
    print( Fore.WHITE + f'Root mean squared error of testing: {RMSE_test}' )

## Pre-Processing

In [38]:
knn_Pipeline

Pipeline(steps=[('One-Hor Encoding',
                 ColumnTransformer(remainder='passthtrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['sex', 'fasting_blood_sugar',
                                                   'rest_ecg', 'diagnosis',
                                                   'st_slope',
                                                   'exercise_induced_angina'])])),
                ('model', KNeighborsRegressor(n_neighbors=7))])

# Error wegen: daten sind schon als One-Hoting gesetzt

In [41]:
# knn_Pipeline.fit( X_train, y_train )
# Error wegen: daten sind schon als One-Hoting gesetzt